export const ROUTES = {
    WELCOME: '/',
    MAP: '/map',
    THEATRE_WORLD: '/map/theatre-world',
    THEATRE_WORLD_GENDER: '/map/theatre-world/gender',
    THEATRE_WORLD_GENDER_CORRECTION: '/map/theatre-world/gender/correction',
    THEATRE_WORLD_IMAGE_THEATRE: '/map/theatre-world/image-theatre',
    THEATRE_WORLD_DISABILITY: '/map/theatre-world/image-theatre/disability',
    THEATRE_WORLD_DISABILITY_CORRECTION: '/map/theatre-world/image-theatre/disability/correction',
    THEATRE_WORLD_IMAGE_THEATRE_CORRECTION: '/map/theatre-world/image-theatre/correction',
    THEATRE_WORLD_GAMES: '/map/theatre-world/games',
    THEATRE_WORLD_GAMES_QUIZ: '/map/theatre-world/games/quiz/:difficulty',
    THEATRE_WORLD_FORUM: '/map/theatre-world/forum-theatre',
    THEATRE_WORLD_FORUM_QUIZ: '/map/theatre-world/forum-theatre/quiz/:difficulty',
    THEATRE_WORLD_IMAGE_THEATRE_EDUCATION: '/map/theatre-world/image-theatre/education',
    THEATRE_WORLD_IMAGE_THEATRE_EDUCATION_CORRECTION: '/map/theatre-world/image-theatre/education/correction',
    THEATRE_WORLD_IMAGE_THEATRE_SPORTS: '/map/theatre-world/image-theatre/sports',
    THEATRE_WORLD_IMAGE_THEATRE_SPORTS_CORRECTION: '/map/theatre-world/image-theatre/sports/correction',
    THEATRE_WORLD_IMAGE_THEATRE_PRESS: '/map/theatre-world/image-theatre/press',
    THEATRE_WORLD_IMAGE_THEATRE_PRESS_CORRECTION: '/map/theatre-world/image-theatre/press/correction',
    THEATRE_WORLD_IMAGE_THEATRE_PEACE_AGENDA: '/map/theatre-world/image-theatre/peace-agenda',
    THEATRE_WORLD_IMAGE_THEATRE_PEACE_AGENDA_CORRECTION: '/map/theatre-world/image-theatre/peace-agenda/correction',
    LAW_WORLD: '/map/law-world',
    LAW_WORLD_GENERAL_PROVISIONS: '/map/law-world/general-provisions',
    LAW_WORLD_GENERAL_PROVISIONS_QUIZ: '/map/law-world/general-provisions/quiz',
    LAW_WORLD_GENERAL_PROVISIONS_CORRECTION: '/map/law-world/general-provisions/correction',
    LAW_WORLD_CRIMINALIZATION: '/map/law-world/criminalization',
    LAW_WORLD_CRIMINALIZATION_CORRECTION: '/map/law-world/criminalization/correction',
    POLICY_WORLD: '/map/policy-world',
    POLICY_WORLD_KNOWLEDGE: '/map/policy-world/knowledge',
    POLICY_WORLD_KNOWLEDGE_QUIZ: '/map/policy-world/knowledge/quiz',
    POLICY_WORLD_DEBATE: '/map/policy-world/debate',
    POLICY_WORLD_DEBATE_CORRECTION: '/map/policy-world/debate/correction',
    POLICY_WORLD_ACADEMIA: '/map/policy-world/academia',
    POLICY_WORLD_ACADEMIA_MODULE_1: '/map/policy-world/academia/module/1',
    POLICY_WORLD_ACADEMIA_MODULE_1_CORRECTION: '/map/policy-world/academia/module/1/correction',
    POLICY_WORLD_ACADEMIA_MODULE_2: '/map/policy-world/academia/module/2',
    POLICY_WORLD_ACADEMIA_MODULE_2_CORRECTION: '/map/policy-world/academia/module/2/correction',
    POLICY_WORLD_ACADEMIA_MODULE_3: '/map/policy-world/academia/module/3',
    POLICY_WORLD_ACADEMIA_MODULE_3_CORRECTION: '/map/policy-world/academia/module/3/correction',
    POLICY_WORLD_ACADEMIA_MODULE_4: '/map/policy-world/academia/module/4',
    POLICY_WORLD_ACADEMIA_MODULE_4_CORRECTION: '/map/policy-world/academia/module/4/correction',
    CALL: '/call',
} as const;


